### ISSUE TITLE
Node 16 actions are getting deprecated

### ISSUE THREAD

**Issue by mattbrandlysonos** [transferwise/actions-next-bundle-analyzer#41]
More details here: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Should be a trivial change:
https://github.com/transferwise/actions-next-bundle-analyzer/blob/4277633c21d084fe92f75bfe8921ddd93d002262/action.yml#L12

**Comment by Wise-StenRaudmets** [comment]
This is resolved in the v2 branch which is also now the default branch:
https://github.com/transferwise/actions-next-bundle-analyzer/blob/aa7c3f926cc3672196a9f012bf11374c79011835/action.yml#L4
